accounts:
  redis:
    username: server
    password: propteambestteam
  camera:
    username: propcam
    password: propteambestteam

services:
  redis:
    ip: localhost
    port: 6379
  mediamtx:
    ip: localhost
    api_port: 9997
    webrtc_port: 8889 # Relayed to GUI for connection

cameras:
  - ip: 192.168.1.5
    onvif_port: 2020
  - ip: 192.168.1.6
    onvif_port: 2020
  - ip: 192.168.1.7
    onvif_port: 2020