accounts:
  redis:
    username: server
    password: propteambestteam
  camera:
    username: propcam
    password: propteambestteam

mediamtx:
  ip: localhost
  port: 9997

cameras:
  - ip: 192.168.1.5
    onvif_port: 2020
  - ip: 192.168.1.6
    onvif_port: 2020
  - ip: 192.168.1.7
    onvif_port: 2020