version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - absjoin
  - aioconsole
  - AVFILL
  - colorama
  - csvfile
  - DEVICECOMMANDS
  - DGRAM
  - dlog
  - DUMBASS
  - ECONNRESET
  - elog
  - espdevice
  - essid
  - figsize
  - getch
  - gethostname
  - INADDR
  - IPPROTO
  - ipykernel
  - isconnected
  - kbhit
  - labjack
  - libqretprop
  - matplotlib
  - microcontroller
  - micropython
  - Modbus
  - mpremote
  - mreq
  - mylogging
  - Nikhil
  - numpy
  - osdebug
  - pyproject
  - pyqtgraph
  - QRET
  - qretprop
  - qretproptools
  - REUSEADDR
  - REUSEPORT
  - SERVERCOMMANDS
  - showlegend
  - skiprows
  - SSDP
  - STRM
  - teststand
  - timesync
  - webrepl
  - WLAN
  - xaxes
  - yaxes
  - ylim
ignoreWords: []
import: []
